from configparser import ConfigParser
import features_check

class read() :
    def __init__(self, *args) :
        config = ConfigParser()

        while True :
            try :
                with open("configs/last/last.txt", "r") as f :
                    for line in f :
                        last = line

                        config.read('configs/'+last)

                        if args :
                            if args[0] == "glow" :
                                features_check.check.glow_active = config.getboolean('VISUALS', 'glow_active')
                                features_check.check.glow_health_based = config.getboolean('VISUALS', 'glow_health_based')
                                features_check.check.glow_ennemies = config.getboolean('VISUALS', 'glow_ennemies')
                                features_check.check.ennemies_glow_color = config.get('VISUALS', 'ennemies_glow_color')
                                features_check.check.glow_allies = config.getboolean('VISUALS', 'glow_allies')
                                features_check.check.allies_glow_color = config.get('VISUALS', 'allies_glow_color')
                                return
                        
                            elif args[0] == "chams" :
                                features_check.check.chams_active = config.getboolean('VISUALS', 'chams_active')
                                features_check.check.chams_health_based = config.getboolean('VISUALS', 'chams_health_based')
                                features_check.check.chams_ennemies = config.getboolean('VISUALS', 'chams_ennemies')
                                features_check.check.ennemies_chams_color = config.get('VISUALS', 'ennemies_chams_color')
                                features_check.check.chams_allies = config.getboolean('VISUALS', 'chams_allies')
                                features_check.check.allies_chams_color = config.get('VISUALS', 'allies_chams_color')
                                return
                            
                            elif args[0] == "aim" :
                                features_check.check.aimbot = config.getboolean('AIM', 'aimbot')
                                features_check.check.aimbot_key = config.get('AIM', 'aimbot_key')
                                features_check.check.silent_aim = config.getboolean('AIM', 'silent_aim')
                                features_check.check.silent_aim_key = config.get('AIM', 'silent_aim_key')
                                features_check.check.crosshair = config.getboolean('AIM', 'crosshair')
                                return
                            
                            elif args[0] == "rcs" :
                                features_check.check.rcs = config.getboolean('AIM', 'rcs')
                                features_check.check.rcs_perfect = config.getfloat('AIM', 'rcs_perfect')
                                return

                            elif args[0] == "triggerbot" :
                                features_check.check.triggerbot = config.getboolean('AIM', 'triggerbot')
                                features_check.check.t_delay = config.getfloat('AIM', 't_delay')
                                features_check.check.triggerbot_key = config.get('AIM', 'triggerbot_key')
                                return

                            elif args[0] == "rapid fire" :
                                features_check.check.rapid_fire = config.getboolean('AIM', 'rapid_fire')
                                features_check.check.rapid_fire_key = config.get('AIM', 'rapid_fire_key')
                                return

                            elif args[0] == "misc" :
                                features_check.check.third_person = config.getboolean('MISC', 'third_person')
                                features_check.check.thirdperson_key = config.get('MISC', 'thirdperson_key')
                                features_check.check.fov = config.getboolean('MISC', 'fov')
                                features_check.check.fov_value = config.getfloat('MISC', 'fov_value')
                                features_check.check.hitsound = config.getboolean('MISC', 'hitsound')
                                features_check.check.sound = config.get('MISC', 'sound')
                                features_check.check.sound_esp = config.getboolean('MISC', 'sound_esp')
                                features_check.check.no_flash = config.getboolean('MISC', 'no_flash')
                                features_check.check.bhop_rage = config.getboolean('MISC', 'bhop_rage')
                                features_check.check.bhop_legit = config.getboolean('MISC', 'bhop_legit')
                                features_check.check.show_money = config.getboolean('MISC', 'show_money')
                                features_check.check.radar = config.getboolean('MISC', 'radar')
                                features_check.check.fake_lag = config.getboolean('MISC', 'fake_lag')
                                features_check.check.fake_lag_value = config.getfloat('MISC', 'fake_lag_value')
                                return
                            
                            elif args[0] == "skinchanger" :
                                #SKINCHANGER
                                features_check.check.AK47 = config.get('SKINCHANGER', 'AK47')
                                features_check.check.AK47_f = config.get('SKINCHANGER', 'AK47_f')
                                features_check.check.AK47_st = config.get('SKINCHANGER', 'AK47_st')
                                features_check.check.AK47_stv = config.get('SKINCHANGER', 'AK47_stv')
                                features_check.check.AK47_se = config.get('SKINCHANGER', 'AK47_se')
                                features_check.check.AUG = config.get('SKINCHANGER', 'AUG')
                                features_check.check.AUG_f = config.get('SKINCHANGER', 'AUG_f')
                                features_check.check.AUG_st = config.get('SKINCHANGER', 'AUG_st')
                                features_check.check.AUG_stv = config.get('SKINCHANGER', 'AUG_stv')
                                features_check.check.AUG_se = config.get('SKINCHANGER', 'AUG_se')
                                features_check.check.AWP = config.get('SKINCHANGER', 'AWP')
                                features_check.check.AWP_f = config.get('SKINCHANGER', 'AWP_f')
                                features_check.check.AWP_st = config.get('SKINCHANGER', 'AWP_st')
                                features_check.check.AWP_stv = config.get('SKINCHANGER', 'AWP_stv')
                                features_check.check.AWP_se = config.get('SKINCHANGER', 'AWP_se')
                                features_check.check.CZ75Auto = config.get('SKINCHANGER', 'CZ75Auto')
                                features_check.check.CZ75Auto_f = config.get('SKINCHANGER', 'CZ75Auto_f')
                                features_check.check.CZ75Auto_st = config.get('SKINCHANGER', 'CZ75Auto_st')
                                features_check.check.CZ75Auto_stv = config.get('SKINCHANGER', 'CZ75Auto_stv')
                                features_check.check.CZ75Auto_se = config.get('SKINCHANGER', 'CZ75Auto_se')
                                features_check.check.Desert_Eagle = config.get('SKINCHANGER', 'Desert_Eagle')
                                features_check.check.Desert_Eagle_f = config.get('SKINCHANGER', 'Desert_Eagle_f')
                                features_check.check.Desert_Eagle_st = config.get('SKINCHANGER', 'Desert_Eagle_st')
                                features_check.check.Desert_Eagle_stv = config.get('SKINCHANGER', 'Desert_Eagle_stv')
                                features_check.check.Desert_Eagle_se = config.get('SKINCHANGER', 'Desert_Eagle_se')
                                features_check.check.Dual_Berettas = config.get('SKINCHANGER', 'Dual_Berettas')
                                features_check.check.Dual_Berettas_f = config.get('SKINCHANGER', 'Dual_Berettas_f')
                                features_check.check.Dual_Berettas_st = config.get('SKINCHANGER', 'Dual_Berettas_st')
                                features_check.check.Dual_Berettas_stv = config.get('SKINCHANGER', 'Dual_Berettas_stv')
                                features_check.check.Dual_Berettas_se = config.get('SKINCHANGER', 'Dual_Berettas_se')
                                features_check.check.FAMAS = config.get('SKINCHANGER', 'FAMAS')
                                features_check.check.FAMAS_f = config.get('SKINCHANGER', 'FAMAS_f')
                                features_check.check.FAMAS_st = config.get('SKINCHANGER', 'FAMAS_st')
                                features_check.check.FAMAS_stv = config.get('SKINCHANGER', 'FAMAS_stv')
                                features_check.check.FAMAS_se = config.get('SKINCHANGER', 'FAMAS_se')
                                features_check.check.FiveSeven = config.get('SKINCHANGER', 'FiveSeven')
                                features_check.check.FiveSeven_f = config.get('SKINCHANGER', 'FiveSeven_f')
                                features_check.check.FiveSeven_st = config.get('SKINCHANGER', 'FiveSeven_st')
                                features_check.check.FiveSeven_stv = config.get('SKINCHANGER', 'FiveSeven_stv')
                                features_check.check.FiveSeven_se = config.get('SKINCHANGER', 'FiveSeven_se')
                                features_check.check.G3SG1 = config.get('SKINCHANGER', 'G3SG1')
                                features_check.check.G3SG1_f = config.get('SKINCHANGER', 'G3SG1_f')
                                features_check.check.G3SG1_st = config.get('SKINCHANGER', 'G3SG1_st')
                                features_check.check.G3SG1_stv = config.get('SKINCHANGER', 'G3SG1_stv')
                                features_check.check.G3SG1_se = config.get('SKINCHANGER', 'G3SG1_se')
                                features_check.check.Galil_AR = config.get('SKINCHANGER', 'Galil_AR')
                                features_check.check.Galil_AR_f = config.get('SKINCHANGER', 'Galil_AR_f')
                                features_check.check.Galil_AR_st = config.get('SKINCHANGER', 'Galil_AR_st')
                                features_check.check.Galil_AR_stv = config.get('SKINCHANGER', 'Galil_AR_stv')
                                features_check.check.Galil_AR_se = config.get('SKINCHANGER', 'Galil_AR_se')
                                features_check.check.Glock18 = config.get('SKINCHANGER', 'Glock18')
                                features_check.check.Glock18_f = config.get('SKINCHANGER', 'Glock18_f')
                                features_check.check.Glock18_st = config.get('SKINCHANGER', 'Glock18_st')
                                features_check.check.Glock18_stv = config.get('SKINCHANGER', 'Glock18_stv')
                                features_check.check.Glock18_se = config.get('SKINCHANGER', 'Glock18_se')
                                features_check.check.M249 = config.get('SKINCHANGER', 'M249')
                                features_check.check.M249_f = config.get('SKINCHANGER', 'M249_f')
                                features_check.check.M249_st = config.get('SKINCHANGER', 'M249_st')
                                features_check.check.M249_stv = config.get('SKINCHANGER', 'M249_stv')
                                features_check.check.M249_se = config.get('SKINCHANGER', 'M249_se')
                                features_check.check.M4A1S = config.get('SKINCHANGER', 'M4A1S')
                                features_check.check.M4A1S_f = config.get('SKINCHANGER', 'M4A1S_f')
                                features_check.check.M4A1S_st = config.get('SKINCHANGER', 'M4A1S_st')
                                features_check.check.M4A1S_stv = config.get('SKINCHANGER', 'M4A1S_stv')
                                features_check.check.M4A1S_se = config.get('SKINCHANGER', 'M4A1S_se')
                                features_check.check.M4A4 = config.get('SKINCHANGER', 'M4A4')
                                features_check.check.M4A4_f = config.get('SKINCHANGER', 'M4A4_f')
                                features_check.check.M4A4_st = config.get('SKINCHANGER', 'M4A4_st')
                                features_check.check.M4A4_stv = config.get('SKINCHANGER', 'M4A4_stv')
                                features_check.check.M4A4_se = config.get('SKINCHANGER', 'M4A4_se')
                                features_check.check.MAC10 = config.get('SKINCHANGER', 'MAC10')
                                features_check.check.MAC10_f = config.get('SKINCHANGER', 'MAC10_f')
                                features_check.check.MAC10_st = config.get('SKINCHANGER', 'MAC10_st')
                                features_check.check.MAC10_stv = config.get('SKINCHANGER', 'MAC10_stv')
                                features_check.check.MAC10_se = config.get('SKINCHANGER', 'MAC10_se')
                                features_check.check.MAG7 = config.get('SKINCHANGER', 'MAG7')
                                features_check.check.MAG7_f = config.get('SKINCHANGER', 'MAG7_f')
                                features_check.check.MAG7_st = config.get('SKINCHANGER', 'MAG7_st')
                                features_check.check.MAG7_stv = config.get('SKINCHANGER', 'MAG7_stv')
                                features_check.check.MAG7_se = config.get('SKINCHANGER', 'MAG7_se')
                                features_check.check.MP5SD = config.get('SKINCHANGER', 'MP5SD')
                                features_check.check.MP5SD_f = config.get('SKINCHANGER', 'MP5SD_f')
                                features_check.check.MP5SD_st = config.get('SKINCHANGER', 'MP5SD_st')
                                features_check.check.MP5SD_stv = config.get('SKINCHANGER', 'MP5SD_stv')
                                features_check.check.MP5SD_se = config.get('SKINCHANGER', 'MP5SD_se')
                                features_check.check.MP7 = config.get('SKINCHANGER', 'MP7')
                                features_check.check.MP7_f = config.get('SKINCHANGER', 'MP7_f')
                                features_check.check.MP7_st = config.get('SKINCHANGER', 'MP7_st')
                                features_check.check.MP7_stv = config.get('SKINCHANGER', 'MP7_stv')
                                features_check.check.MP7_se = config.get('SKINCHANGER', 'MP7_se')
                                features_check.check.MP9 = config.get('SKINCHANGER', 'MP9')
                                features_check.check.MP9_f = config.get('SKINCHANGER', 'MP9_f')
                                features_check.check.MP9_st = config.get('SKINCHANGER', 'MP9_st')
                                features_check.check.MP9_stv = config.get('SKINCHANGER', 'MP9_stv')
                                features_check.check.MP9_se = config.get('SKINCHANGER', 'MP9_se')
                                features_check.check.Negev = config.get('SKINCHANGER', 'Negev')
                                features_check.check.Negev_f = config.get('SKINCHANGER', 'Negev_f')
                                features_check.check.Negev_st = config.get('SKINCHANGER', 'Negev_st')
                                features_check.check.Negev_stv = config.get('SKINCHANGER', 'Negev_stv')
                                features_check.check.Negev_se = config.get('SKINCHANGER', 'Negev_se')
                                features_check.check.Nova = config.get('SKINCHANGER', 'Nova')
                                features_check.check.Nova_f = config.get('SKINCHANGER', 'Nova_f')
                                features_check.check.Nova_st = config.get('SKINCHANGER', 'Nova_st')
                                features_check.check.Nova_stv = config.get('SKINCHANGER', 'Nova_stv')
                                features_check.check.Nova_se = config.get('SKINCHANGER', 'Nova_se')
                                features_check.check.P2000 = config.get('SKINCHANGER', 'P2000')
                                features_check.check.P2000_f = config.get('SKINCHANGER', 'P2000_f')
                                features_check.check.P2000_st = config.get('SKINCHANGER', 'P2000_st')
                                features_check.check.P2000_stv = config.get('SKINCHANGER', 'P2000_stv')
                                features_check.check.P2000_se = config.get('SKINCHANGER', 'P2000_se')
                                features_check.check.P250 = config.get('SKINCHANGER', 'P250')
                                features_check.check.P250_f = config.get('SKINCHANGER', 'P250_f')
                                features_check.check.P250_st = config.get('SKINCHANGER', 'P250_st')
                                features_check.check.P250_stv = config.get('SKINCHANGER', 'P250_stv')
                                features_check.check.P250_se = config.get('SKINCHANGER', 'P250_se')
                                features_check.check.P90 = config.get('SKINCHANGER', 'P90')
                                features_check.check.P90_f = config.get('SKINCHANGER', 'P90_f')
                                features_check.check.P90_st = config.get('SKINCHANGER', 'P90_st')
                                features_check.check.P90_stv = config.get('SKINCHANGER', 'P90_stv')
                                features_check.check.P90_se = config.get('SKINCHANGER', 'P90_se')
                                features_check.check.PPBizon = config.get('SKINCHANGER', 'PPBizon')
                                features_check.check.PPBizon_f = config.get('SKINCHANGER', 'PPBizon_f')
                                features_check.check.PPBizon_st = config.get('SKINCHANGER', 'PPBizon_st')
                                features_check.check.PPBizon_stv = config.get('SKINCHANGER', 'PPBizon_stv')
                                features_check.check.PPBizon_se = config.get('SKINCHANGER', 'PPBizon_se')
                                features_check.check.R8_Revolver = config.get('SKINCHANGER', 'R8_Revolver')
                                features_check.check.R8_Revolver_f = config.get('SKINCHANGER', 'R8_Revolver_f')
                                features_check.check.R8_Revolver_st = config.get('SKINCHANGER', 'R8_Revolver_st')
                                features_check.check.R8_Revolver_stv = config.get('SKINCHANGER', 'R8_Revolver_stv')
                                features_check.check.R8_Revolver_se = config.get('SKINCHANGER', 'R8_Revolver_se')
                                features_check.check.SCAR20 = config.get('SKINCHANGER', 'SCAR20')
                                features_check.check.SCAR20_f = config.get('SKINCHANGER', 'SCAR20_f')
                                features_check.check.SCAR20_st = config.get('SKINCHANGER', 'SCAR20_st')
                                features_check.check.SCAR20_stv = config.get('SKINCHANGER', 'SCAR20_stv')
                                features_check.check.SCAR20_se = config.get('SKINCHANGER', 'SCAR20_se')
                                features_check.check.SG_553 = config.get('SKINCHANGER', 'SG_553')
                                features_check.check.SG_553_f = config.get('SKINCHANGER', 'SG_553_f')
                                features_check.check.SG_553_st = config.get('SKINCHANGER', 'SG_553_st')
                                features_check.check.SG_553_stv = config.get('SKINCHANGER', 'SG_553_stv')
                                features_check.check.SG_553_se = config.get('SKINCHANGER', 'SG_553_se')
                                features_check.check.SSG_08 = config.get('SKINCHANGER', 'SSG_08')
                                features_check.check.SSG_08_f = config.get('SKINCHANGER', 'SSG_08_f')
                                features_check.check.SSG_08_st = config.get('SKINCHANGER', 'SSG_08_st')
                                features_check.check.SSG_08_stv = config.get('SKINCHANGER', 'SSG_08_stv')
                                features_check.check.SSG_08_se = config.get('SKINCHANGER', 'SSG_08_se')
                                features_check.check.SawedOff = config.get('SKINCHANGER', 'SawedOff')
                                features_check.check.SawedOff_f = config.get('SKINCHANGER', 'SawedOff_f')
                                features_check.check.SawedOff_st = config.get('SKINCHANGER', 'SawedOff_st')
                                features_check.check.SawedOff_stv = config.get('SKINCHANGER', 'SawedOff_stv')
                                features_check.check.SawedOff_se = config.get('SKINCHANGER', 'SawedOff_se')
                                features_check.check.Tec9 = config.get('SKINCHANGER', 'Tec9')
                                features_check.check.Tec9_f = config.get('SKINCHANGER', 'Tec9_f')
                                features_check.check.Tec9_st = config.get('SKINCHANGER', 'Tec9_st')
                                features_check.check.Tec9_stv = config.get('SKINCHANGER', 'Tec9_stv')
                                features_check.check.Tec9_se = config.get('SKINCHANGER', 'Tec9_se')
                                features_check.check.UMP45 = config.get('SKINCHANGER', 'UMP45')
                                features_check.check.UMP45_f = config.get('SKINCHANGER', 'UMP45_f')
                                features_check.check.UMP45_st = config.get('SKINCHANGER', 'UMP45_st')
                                features_check.check.UMP45_stv = config.get('SKINCHANGER', 'UMP45_stv')
                                features_check.check.UMP45_se = config.get('SKINCHANGER', 'UMP45_se')
                                features_check.check.USPS = config.get('SKINCHANGER', 'USPS')
                                features_check.check.USPS_f = config.get('SKINCHANGER', 'USPS_f')
                                features_check.check.USPS_st = config.get('SKINCHANGER', 'USPS_st')
                                features_check.check.USPS_stv = config.get('SKINCHANGER', 'USPS_stv')
                                features_check.check.USPS_se = config.get('SKINCHANGER', 'USPS_se')
                                features_check.check.XM1014 = config.get('SKINCHANGER', 'XM1014')
                                features_check.check.XM1014_f = config.get('SKINCHANGER', 'XM1014_f')
                                features_check.check.XM1014_st = config.get('SKINCHANGER', 'XM1014_st')
                                features_check.check.XM1014_stv = config.get('SKINCHANGER', 'XM1014_stv')
                                features_check.check.XM1014_se = config.get('SKINCHANGER', 'XM1014_se')
                                return

                        #VISUALS
                        features_check.check.glow_active = config.getboolean('VISUALS', 'glow_active')
                        features_check.check.glow_health_based = config.getboolean('VISUALS', 'glow_health_based')
                        features_check.check.glow_ennemies = config.getboolean('VISUALS', 'glow_ennemies')
                        features_check.check.ennemies_glow_color = config.get('VISUALS', 'ennemies_glow_color')
                        features_check.check.glow_allies = config.getboolean('VISUALS', 'glow_allies')
                        features_check.check.allies_glow_color = config.get('VISUALS', 'allies_glow_color')
                        features_check.check.chams_active = config.getboolean('VISUALS', 'chams_active')
                        features_check.check.chams_health_based = config.getboolean('VISUALS', 'chams_health_based')
                        features_check.check.chams_ennemies = config.getboolean('VISUALS', 'chams_ennemies')
                        features_check.check.ennemies_chams_color = config.get('VISUALS', 'ennemies_chams_color')
                        features_check.check.chams_allies = config.getboolean('VISUALS', 'chams_allies')
                        features_check.check.allies_chams_color = config.get('VISUALS', 'allies_chams_color')

                        #AIM
                        features_check.check.aimbot = config.getboolean('AIM', 'aimbot')
                        features_check.check.aimbot_key = config.get('AIM', 'aimbot_key')
                        features_check.check.rcs = config.getboolean('AIM', 'rcs')
                        features_check.check.rcs_perfect = config.getfloat('AIM', 'rcs_perfect')
                        features_check.check.triggerbot = config.getboolean('AIM', 'triggerbot')
                        features_check.check.t_delay = config.getfloat('AIM', 't_delay')
                        features_check.check.triggerbot_key = config.get('AIM', 'triggerbot_key')
                        features_check.check.rapid_fire = config.getboolean('AIM', 'rapid_fire')
                        features_check.check.rapid_fire_key = config.get('AIM', 'rapid_fire_key')
                        features_check.check.silent_aim = config.getboolean('AIM', 'silent_aim')
                        features_check.check.silent_aim_key = config.get('AIM', 'silent_aim_key')
                        features_check.check.crosshair = config.getboolean('AIM', 'crosshair')

                        #MISC
                        features_check.check.third_person = config.getboolean('MISC', 'third_person')
                        features_check.check.thirdperson_key = config.get('MISC', 'thirdperson_key')
                        features_check.check.fov = config.getboolean('MISC', 'fov')
                        features_check.check.fov_value = config.getfloat('MISC', 'fov_value')
                        features_check.check.hitsound = config.getboolean('MISC', 'hitsound')
                        features_check.check.sound = config.get('MISC', 'sound')
                        features_check.check.sound_esp = config.getboolean('MISC', 'sound_esp')
                        features_check.check.no_flash = config.getboolean('MISC', 'no_flash')
                        features_check.check.bhop_rage = config.getboolean('MISC', 'bhop_rage')
                        features_check.check.bhop_legit = config.getboolean('MISC', 'bhop_legit')
                        features_check.check.show_money = config.getboolean('MISC', 'show_money')
                        features_check.check.radar = config.getboolean('MISC', 'radar')
                        features_check.check.fake_lag = config.getboolean('MISC', 'fake_lag')
                        features_check.check.fake_lag_value = config.getfloat('MISC', 'fake_lag_value')

                        #SETTINGS
                        features_check.check.ui_color = config.get('SETTINGS', 'ui_color')

                        #SKINCHANGER
                        features_check.check.AK47 = config.get('SKINCHANGER', 'AK47')
                        features_check.check.AK47_f = config.get('SKINCHANGER', 'AK47_f')
                        features_check.check.AK47_st = config.get('SKINCHANGER', 'AK47_st')
                        features_check.check.AK47_stv = config.get('SKINCHANGER', 'AK47_stv')
                        features_check.check.AK47_se = config.get('SKINCHANGER', 'AK47_se')
                        features_check.check.AUG = config.get('SKINCHANGER', 'AUG')
                        features_check.check.AUG_f = config.get('SKINCHANGER', 'AUG_f')
                        features_check.check.AUG_st = config.get('SKINCHANGER', 'AUG_st')
                        features_check.check.AUG_stv = config.get('SKINCHANGER', 'AUG_stv')
                        features_check.check.AUG_se = config.get('SKINCHANGER', 'AUG_se')
                        features_check.check.AWP = config.get('SKINCHANGER', 'AWP')
                        features_check.check.AWP_f = config.get('SKINCHANGER', 'AWP_f')
                        features_check.check.AWP_st = config.get('SKINCHANGER', 'AWP_st')
                        features_check.check.AWP_stv = config.get('SKINCHANGER', 'AWP_stv')
                        features_check.check.AWP_se = config.get('SKINCHANGER', 'AWP_se')
                        features_check.check.CZ75Auto = config.get('SKINCHANGER', 'CZ75Auto')
                        features_check.check.CZ75Auto_f = config.get('SKINCHANGER', 'CZ75Auto_f')
                        features_check.check.CZ75Auto_st = config.get('SKINCHANGER', 'CZ75Auto_st')
                        features_check.check.CZ75Auto_stv = config.get('SKINCHANGER', 'CZ75Auto_stv')
                        features_check.check.CZ75Auto_se = config.get('SKINCHANGER', 'CZ75Auto_se')
                        features_check.check.Desert_Eagle = config.get('SKINCHANGER', 'Desert_Eagle')
                        features_check.check.Desert_Eagle_f = config.get('SKINCHANGER', 'Desert_Eagle_f')
                        features_check.check.Desert_Eagle_st = config.get('SKINCHANGER', 'Desert_Eagle_st')
                        features_check.check.Desert_Eagle_stv = config.get('SKINCHANGER', 'Desert_Eagle_stv')
                        features_check.check.Desert_Eagle_se = config.get('SKINCHANGER', 'Desert_Eagle_se')
                        features_check.check.Dual_Berettas = config.get('SKINCHANGER', 'Dual_Berettas')
                        features_check.check.Dual_Berettas_f = config.get('SKINCHANGER', 'Dual_Berettas_f')
                        features_check.check.Dual_Berettas_st = config.get('SKINCHANGER', 'Dual_Berettas_st')
                        features_check.check.Dual_Berettas_stv = config.get('SKINCHANGER', 'Dual_Berettas_stv')
                        features_check.check.Dual_Berettas_se = config.get('SKINCHANGER', 'Dual_Berettas_se')
                        features_check.check.FAMAS = config.get('SKINCHANGER', 'FAMAS')
                        features_check.check.FAMAS_f = config.get('SKINCHANGER', 'FAMAS_f')
                        features_check.check.FAMAS_st = config.get('SKINCHANGER', 'FAMAS_st')
                        features_check.check.FAMAS_stv = config.get('SKINCHANGER', 'FAMAS_stv')
                        features_check.check.FAMAS_se = config.get('SKINCHANGER', 'FAMAS_se')
                        features_check.check.FiveSeven = config.get('SKINCHANGER', 'FiveSeven')
                        features_check.check.FiveSeven_f = config.get('SKINCHANGER', 'FiveSeven_f')
                        features_check.check.FiveSeven_st = config.get('SKINCHANGER', 'FiveSeven_st')
                        features_check.check.FiveSeven_stv = config.get('SKINCHANGER', 'FiveSeven_stv')
                        features_check.check.FiveSeven_se = config.get('SKINCHANGER', 'FiveSeven_se')
                        features_check.check.G3SG1 = config.get('SKINCHANGER', 'G3SG1')
                        features_check.check.G3SG1_f = config.get('SKINCHANGER', 'G3SG1_f')
                        features_check.check.G3SG1_st = config.get('SKINCHANGER', 'G3SG1_st')
                        features_check.check.G3SG1_stv = config.get('SKINCHANGER', 'G3SG1_stv')
                        features_check.check.G3SG1_se = config.get('SKINCHANGER', 'G3SG1_se')
                        features_check.check.Galil_AR = config.get('SKINCHANGER', 'Galil_AR')
                        features_check.check.Galil_AR_f = config.get('SKINCHANGER', 'Galil_AR_f')
                        features_check.check.Galil_AR_st = config.get('SKINCHANGER', 'Galil_AR_st')
                        features_check.check.Galil_AR_stv = config.get('SKINCHANGER', 'Galil_AR_stv')
                        features_check.check.Galil_AR_se = config.get('SKINCHANGER', 'Galil_AR_se')
                        features_check.check.Glock18 = config.get('SKINCHANGER', 'Glock18')
                        features_check.check.Glock18_f = config.get('SKINCHANGER', 'Glock18_f')
                        features_check.check.Glock18_st = config.get('SKINCHANGER', 'Glock18_st')
                        features_check.check.Glock18_stv = config.get('SKINCHANGER', 'Glock18_stv')
                        features_check.check.Glock18_se = config.get('SKINCHANGER', 'Glock18_se')
                        features_check.check.M249 = config.get('SKINCHANGER', 'M249')
                        features_check.check.M249_f = config.get('SKINCHANGER', 'M249_f')
                        features_check.check.M249_st = config.get('SKINCHANGER', 'M249_st')
                        features_check.check.M249_stv = config.get('SKINCHANGER', 'M249_stv')
                        features_check.check.M249_se = config.get('SKINCHANGER', 'M249_se')
                        features_check.check.M4A1S = config.get('SKINCHANGER', 'M4A1S')
                        features_check.check.M4A1S_f = config.get('SKINCHANGER', 'M4A1S_f')
                        features_check.check.M4A1S_st = config.get('SKINCHANGER', 'M4A1S_st')
                        features_check.check.M4A1S_stv = config.get('SKINCHANGER', 'M4A1S_stv')
                        features_check.check.M4A1S_se = config.get('SKINCHANGER', 'M4A1S_se')
                        features_check.check.M4A4 = config.get('SKINCHANGER', 'M4A4')
                        features_check.check.M4A4_f = config.get('SKINCHANGER', 'M4A4_f')
                        features_check.check.M4A4_st = config.get('SKINCHANGER', 'M4A4_st')
                        features_check.check.M4A4_stv = config.get('SKINCHANGER', 'M4A4_stv')
                        features_check.check.M4A4_se = config.get('SKINCHANGER', 'M4A4_se')
                        features_check.check.MAC10 = config.get('SKINCHANGER', 'MAC10')
                        features_check.check.MAC10_f = config.get('SKINCHANGER', 'MAC10_f')
                        features_check.check.MAC10_st = config.get('SKINCHANGER', 'MAC10_st')
                        features_check.check.MAC10_stv = config.get('SKINCHANGER', 'MAC10_stv')
                        features_check.check.MAC10_se = config.get('SKINCHANGER', 'MAC10_se')
                        features_check.check.MAG7 = config.get('SKINCHANGER', 'MAG7')
                        features_check.check.MAG7_f = config.get('SKINCHANGER', 'MAG7_f')
                        features_check.check.MAG7_st = config.get('SKINCHANGER', 'MAG7_st')
                        features_check.check.MAG7_stv = config.get('SKINCHANGER', 'MAG7_stv')
                        features_check.check.MAG7_se = config.get('SKINCHANGER', 'MAG7_se')
                        features_check.check.MP5SD = config.get('SKINCHANGER', 'MP5SD')
                        features_check.check.MP5SD_f = config.get('SKINCHANGER', 'MP5SD_f')
                        features_check.check.MP5SD_st = config.get('SKINCHANGER', 'MP5SD_st')
                        features_check.check.MP5SD_stv = config.get('SKINCHANGER', 'MP5SD_stv')
                        features_check.check.MP5SD_se = config.get('SKINCHANGER', 'MP5SD_se')
                        features_check.check.MP7 = config.get('SKINCHANGER', 'MP7')
                        features_check.check.MP7_f = config.get('SKINCHANGER', 'MP7_f')
                        features_check.check.MP7_st = config.get('SKINCHANGER', 'MP7_st')
                        features_check.check.MP7_stv = config.get('SKINCHANGER', 'MP7_stv')
                        features_check.check.MP7_se = config.get('SKINCHANGER', 'MP7_se')
                        features_check.check.MP9 = config.get('SKINCHANGER', 'MP9')
                        features_check.check.MP9_f = config.get('SKINCHANGER', 'MP9_f')
                        features_check.check.MP9_st = config.get('SKINCHANGER', 'MP9_st')
                        features_check.check.MP9_stv = config.get('SKINCHANGER', 'MP9_stv')
                        features_check.check.MP9_se = config.get('SKINCHANGER', 'MP9_se')
                        features_check.check.Negev = config.get('SKINCHANGER', 'Negev')
                        features_check.check.Negev_f = config.get('SKINCHANGER', 'Negev_f')
                        features_check.check.Negev_st = config.get('SKINCHANGER', 'Negev_st')
                        features_check.check.Negev_stv = config.get('SKINCHANGER', 'Negev_stv')
                        features_check.check.Negev_se = config.get('SKINCHANGER', 'Negev_se')
                        features_check.check.Nova = config.get('SKINCHANGER', 'Nova')
                        features_check.check.Nova_f = config.get('SKINCHANGER', 'Nova_f')
                        features_check.check.Nova_st = config.get('SKINCHANGER', 'Nova_st')
                        features_check.check.Nova_stv = config.get('SKINCHANGER', 'Nova_stv')
                        features_check.check.Nova_se = config.get('SKINCHANGER', 'Nova_se')
                        features_check.check.P2000 = config.get('SKINCHANGER', 'P2000')
                        features_check.check.P2000_f = config.get('SKINCHANGER', 'P2000_f')
                        features_check.check.P2000_st = config.get('SKINCHANGER', 'P2000_st')
                        features_check.check.P2000_stv = config.get('SKINCHANGER', 'P2000_stv')
                        features_check.check.P2000_se = config.get('SKINCHANGER', 'P2000_se')
                        features_check.check.P250 = config.get('SKINCHANGER', 'P250')
                        features_check.check.P250_f = config.get('SKINCHANGER', 'P250_f')
                        features_check.check.P250_st = config.get('SKINCHANGER', 'P250_st')
                        features_check.check.P250_stv = config.get('SKINCHANGER', 'P250_stv')
                        features_check.check.P250_se = config.get('SKINCHANGER', 'P250_se')
                        features_check.check.P90 = config.get('SKINCHANGER', 'P90')
                        features_check.check.P90_f = config.get('SKINCHANGER', 'P90_f')
                        features_check.check.P90_st = config.get('SKINCHANGER', 'P90_st')
                        features_check.check.P90_stv = config.get('SKINCHANGER', 'P90_stv')
                        features_check.check.P90_se = config.get('SKINCHANGER', 'P90_se')
                        features_check.check.PPBizon = config.get('SKINCHANGER', 'PPBizon')
                        features_check.check.PPBizon_f = config.get('SKINCHANGER', 'PPBizon_f')
                        features_check.check.PPBizon_st = config.get('SKINCHANGER', 'PPBizon_st')
                        features_check.check.PPBizon_stv = config.get('SKINCHANGER', 'PPBizon_stv')
                        features_check.check.PPBizon_se = config.get('SKINCHANGER', 'PPBizon_se')
                        features_check.check.R8_Revolver = config.get('SKINCHANGER', 'R8_Revolver')
                        features_check.check.R8_Revolver_f = config.get('SKINCHANGER', 'R8_Revolver_f')
                        features_check.check.R8_Revolver_st = config.get('SKINCHANGER', 'R8_Revolver_st')
                        features_check.check.R8_Revolver_stv = config.get('SKINCHANGER', 'R8_Revolver_stv')
                        features_check.check.R8_Revolver_se = config.get('SKINCHANGER', 'R8_Revolver_se')
                        features_check.check.SCAR20 = config.get('SKINCHANGER', 'SCAR20')
                        features_check.check.SCAR20_f = config.get('SKINCHANGER', 'SCAR20_f')
                        features_check.check.SCAR20_st = config.get('SKINCHANGER', 'SCAR20_st')
                        features_check.check.SCAR20_stv = config.get('SKINCHANGER', 'SCAR20_stv')
                        features_check.check.SCAR20_se = config.get('SKINCHANGER', 'SCAR20_se')
                        features_check.check.SG_553 = config.get('SKINCHANGER', 'SG_553')
                        features_check.check.SG_553_f = config.get('SKINCHANGER', 'SG_553_f')
                        features_check.check.SG_553_st = config.get('SKINCHANGER', 'SG_553_st')
                        features_check.check.SG_553_stv = config.get('SKINCHANGER', 'SG_553_stv')
                        features_check.check.SG_553_se = config.get('SKINCHANGER', 'SG_553_se')
                        features_check.check.SSG_08 = config.get('SKINCHANGER', 'SSG_08')
                        features_check.check.SSG_08_f = config.get('SKINCHANGER', 'SSG_08_f')
                        features_check.check.SSG_08_st = config.get('SKINCHANGER', 'SSG_08_st')
                        features_check.check.SSG_08_stv = config.get('SKINCHANGER', 'SSG_08_stv')
                        features_check.check.SSG_08_se = config.get('SKINCHANGER', 'SSG_08_se')
                        features_check.check.SawedOff = config.get('SKINCHANGER', 'SawedOff')
                        features_check.check.SawedOff_f = config.get('SKINCHANGER', 'SawedOff_f')
                        features_check.check.SawedOff_st = config.get('SKINCHANGER', 'SawedOff_st')
                        features_check.check.SawedOff_stv = config.get('SKINCHANGER', 'SawedOff_stv')
                        features_check.check.SawedOff_se = config.get('SKINCHANGER', 'SawedOff_se')
                        features_check.check.Tec9 = config.get('SKINCHANGER', 'Tec9')
                        features_check.check.Tec9_f = config.get('SKINCHANGER', 'Tec9_f')
                        features_check.check.Tec9_st = config.get('SKINCHANGER', 'Tec9_st')
                        features_check.check.Tec9_stv = config.get('SKINCHANGER', 'Tec9_stv')
                        features_check.check.Tec9_se = config.get('SKINCHANGER', 'Tec9_se')
                        features_check.check.UMP45 = config.get('SKINCHANGER', 'UMP45')
                        features_check.check.UMP45_f = config.get('SKINCHANGER', 'UMP45_f')
                        features_check.check.UMP45_st = config.get('SKINCHANGER', 'UMP45_st')
                        features_check.check.UMP45_stv = config.get('SKINCHANGER', 'UMP45_stv')
                        features_check.check.UMP45_se = config.get('SKINCHANGER', 'UMP45_se')
                        features_check.check.USPS = config.get('SKINCHANGER', 'USPS')
                        features_check.check.USPS_f = config.get('SKINCHANGER', 'USPS_f')
                        features_check.check.USPS_st = config.get('SKINCHANGER', 'USPS_st')
                        features_check.check.USPS_stv = config.get('SKINCHANGER', 'USPS_stv')
                        features_check.check.USPS_se = config.get('SKINCHANGER', 'USPS_se')
                        features_check.check.XM1014 = config.get('SKINCHANGER', 'XM1014')
                        features_check.check.XM1014_f = config.get('SKINCHANGER', 'XM1014_f')
                        features_check.check.XM1014_st = config.get('SKINCHANGER', 'XM1014_st')
                        features_check.check.XM1014_stv = config.get('SKINCHANGER', 'XM1014_stv')
                        features_check.check.XM1014_se = config.get('SKINCHANGER', 'XM1014_se')
                        return
                        
            except Exception as e:
                pass